# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - 3.7

stages:
  - test
  - name: answers
    if: branch = master

# Command to run tests, e.g. python setup.py test
script: python3 -m unittest

jobs:
  include:
    - stage: test
      script: python3 -m unittest -v
    - stage: answers
      script: python3 fibonacci.py
      name: "Fibonacci"
    - script: python3 pyramid.py
      name: "Pyramid"